language: csharp
solution: src/GitTools.Core.sln
sudo: false
dotnet: 2.1.300
dist: trusty
mono: none
install:
  # - sudo nuget update -self
  - dotnet restore "./src/GitTools.Core.sln"
script:
  - dotnet restore "./src/GitTools.Core.Tests/GitTools.Core.Tests.csproj" /p:TargetFramework=netcoreapp2.0 /verbosity:detailed
  - dotnet build "./src/GitTools.Core.Tests/GitTools.Core.Tests.csproj" --configuration Debug --framework netcoreapp2.0 /verbosity:detailed
  - dotnet test "./src/GitTools.Core.Tests/GitTools.Core.Tests.csproj" --framework netcoreapp2.0 --filter TestCategory!=NoMono
  # - mono --debug --runtime=v4.0.30319 %userprofile%.nuget/packages/nunit.consolerunner/3.6.1/tools/nunit3-console.exe ./output/debug/GitTools.Core.Tests/net45/GitTools.Core.Tests.dll -where "cat != NoMono"
