language: csharp
solution: src/GitTools.Core.sln
dotnet: 2.1.503
mono: none
install:
  # - sudo nuget update -self
  - dotnet restore "./src/GitTools.Core.sln"
script:
  - dotnet restore "./src/GitTools.Core.Tests/GitTools.Core.Tests.csproj" /p:TargetFramework=netcoreapp2.1 /verbosity:detailed
  - dotnet build "./src/GitTools.Core.Tests/GitTools.Core.Tests.csproj" --configuration Debug --framework netcoreapp2.1 /verbosity:detailed
  - dotnet test "./src/GitTools.Core.Tests/GitTools.Core.Tests.csproj" --framework netcoreapp2.1 --filter TestCategory!=NoMono
  # - mono --debug --runtime=v4.0.30319 %userprofile%.nuget/packages/nunit.consolerunner/3.9.0/tools/nunit3-console.exe ./output/debug/GitTools.Core.Tests/net46/GitTools.Core.Tests.dll -where "cat != NoMono"
